### ISSUE TITLE
data 被更新后，网页内容没有被正确更新

### ISSUE THREAD

**Issue by BeiyanYunyi** [one-among-us/web#20]
在 [这个 PR](https://github.com/one-among-us/data/actions/runs/4282938356) 中，我修改了网页内容。但它们没有被正确地应用在[网页上](https://one-among.us/profile/Mio/)

![图片](https://user-images.githubusercontent.com/14120445/221580824-e0870e50-1535-41bc-893b-f5748a917986.png)

网页的 HTML 内容按期望的发生了改变，但引入 js 并注水后，网页回到了它被修改之前的样子。与此同时，[Actions](https://github.com/one-among-us/web/actions/runs/4282944678) Deploy 后提供的 [Preview 网页](https://b9e4dd59.one-among-us.pages.dev/profile/Mio) 却是正常的。

这种现象的原因是，对于每个页面，生成的 js 并没有附带上一串 hash，而是直接以 `page.js` 命名，如 `https://data.one-among.us/people/Mio/page.js`，而 Cloudflare 对这种情况会进行缓存，造成 `page.js` 不能被及时更新上去，从而注水后的页面变成了老页面的样子。缓解的办法是手动更新缓存（在 Cloudflare 控制台那里），根治的办法之一是把 `page.js` 加上 hash，变成类似 `page.1af5b4.js` 的形式。

![图片](https://user-images.githubusercontent.com/14120445/221582260-bf08a7ad-a35b-4942-a055-e7bb540db003.png)

如图可见 Cloudflare 不正确地缓存了这个 js，造成页面更新滞后。

**Comment by sauricat** [comment]
感谢分析！

我在 Cloudflare 控制台里面手动 purge 了一下缓存，暂时性地解决了这个问题。

之后可能考虑调用 purge cache 的 API 来解决这个问题。

**Comment by BeiyanYunyi** [comment]
也可以通过[修改 Page Rules](https://developers.cloudflare.com/cache/how-to/create-page-rules/)、让 Cloudflare 不再缓存 `page.js` 的方式来解决这个问题。

**Comment by BeiyanYunyi** [comment]
Resolved at #24 and one-among-us/data#113 .
