### ISSUE TITLE
【功能讨论】在网页上的回复功能

### ISSUE THREAD

**Issue by BeiyanYunyi** [one-among-us/web#22]
注意到现有评论区可以显示回复，但需要手动在 [data](https://github.com/one-among-us/data) 里加上。不清楚这是未完成还是有意为之。

如果是前者，我可以给前端和后端各提交一份 PR，把这个功能加上。

**Comment by sauricat** [comment]
您好，目前是有意为之的，这个功能一开始做出来的目的是为了对某些可能体现出比较明显抑郁倾向的发言进行可能的干预。目前是不太提倡大家回复的，因为不想把逝者的留言搞得像论坛。有什么话，尽量都对逝者去说吧。
